/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/milestone")
    }

    maven {
        url = uri("https://repo.spring.io/release")
    }

    maven {
        url = uri("https://repo.spring.io/libs-milestone-local")
    }

    maven {
        url = uri("https://repo.spring.io/libs-release-local")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework:spring-context:3.0.7.RELEASE")
    api("org.springframework:spring-jdbc:3.0.7.RELEASE")
    api("org.springframework:spring-webmvc:3.0.7.RELEASE")
    api("org.springframework.security:spring-security-core:3.0.7.RELEASE")
    api("org.springframework.security:spring-security-web:3.0.7.RELEASE")
    api("org.springframework.security:spring-security-taglibs:3.0.7.RELEASE")
    api("org.springframework.security:spring-security-config:3.0.7.RELEASE")
    api("org.springframework.security.oauth:spring-security-oauth2:1.0.0.RELEASE")
    api("org.springframework.integration:spring-integration-core:2.1.3.RELEASE")
    api("org.springframework.integration:spring-integration-http:2.1.3.RELEASE")
    api("org.springframework.integration:spring-integration-mail:2.1.3.RELEASE")
    api("org.springframework.integration:spring-integration-event:2.1.3.RELEASE")
    api("org.springframework.mobile:spring-mobile-device:1.0.0.RELEASE")
    api("org.springframework.social:spring-social-core:1.0.2.RELEASE")
    api("org.springframework.social:spring-social-web:1.0.2.RELEASE")
    api("org.springframework.social:spring-social-facebook:1.0.2.RELEASE")
    api("org.springframework.social:spring-social-facebook-web:1.0.2.RELEASE")
    api("org.springframework.social:spring-social-twitter:1.0.2.RELEASE")
    api("org.aspectj:aspectjrt:1.6.11")
    api("org.springframework:spring-aspects:3.0.7.RELEASE")
    api("cglib:cglib-nodep:2.2")
    api("javax.inject:javax.inject:1")
    api("org.slf4j:slf4j-api:1.6.2")
    api("org.slf4j:jcl-over-slf4j:1.6.2")
    api("com.h2database:h2:1.3.160")
    api("com.google.guava:guava:10.0.1")
    api("org.apache.httpcomponents:httpclient:4.1.2")
    api("javax.mail:mail:1.4.1")
    api("org.antlr:stringtemplate:3.2.1")
    api("javax.servlet.jsp.jstl:jstl-api:1.2")
    api("org.glassfish.web:jstl-impl:1.2")
    api("org.apache.tiles:tiles-jsp:2.2.2")
    api("org.apache.tiles:tiles-el:2.2.2")
    api("javax.validation:validation-api:1.0.0.GA")
    api("org.hibernate:hibernate-validator:4.2.0.Final")
    api("joda-time:joda-time:2.0")
    api("org.codehaus.jackson:jackson-mapper-asl:1.9.9")
    api("commons-fileupload:commons-fileupload:1.2.2")
    api("commons-io:commons-io:1.4")
    api("net.java.dev.jets3t:jets3t:0.8.1")
    api("org.springframework.data:spring-data-redis:1.0.0.RELEASE")
    api("redis.clients:jedis:2.0.0")
    runtimeOnly("org.slf4j:slf4j-log4j12:1.6.2")
    runtimeOnly("log4j:log4j:1.2.16")
    runtimeOnly("joda-time:joda-time-jsptags:1.1")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.hamcrest:hamcrest-library:1.3")
    testImplementation("org.springframework:spring-test:3.0.7.RELEASE")
    testImplementation("org.springframework:spring-test-mvc:1.0.0.M1")
    testImplementation("org.mockito:mockito-core:1.9.0")
    testImplementation("net.sf.opencsv:opencsv:2.3")
    testImplementation("com.jayway.jsonpath:json-path:0.5.5")
    compileOnly("javax.persistence:persistence-api:1.0")
    compileOnly("javax.servlet:servlet-api:2.5")
    compileOnly("javax.servlet.jsp:jsp-api:2.1")
}

group = "com.springsource"
version = "1.0.0.BUILD-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
