/*
 * Copyright 2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.springsource.greenhouse.utils;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 * Utility class for obtaining latitude and longitude of a specified address.
 * Uses Google Maps API to convert addresses to geographic coordinates.
 * 
 * @author Keith Donald
 */
public class GeoLocation {

	private static final String ENCODING = "UTF-8";
	// This is a Google API Key, generated by a member of the UA Spring team, can be
	// changed if needed
	private static final String KEY = "ABQIAAAAtibbxuabc4IbMMd3Lz6YKxT8h4OmK3OACxx2GTyIwybqxjarwRRNysxHsfcnzRtf9nk6CkJc3fb05Q";
	private static final String CSV_PREFIX = "200,6,";

	private String lon;
	private String lat;

	/**
	 * Constructs a GeoLocation with latitude and longitude.
	 */
	private GeoLocation(String lat, String lon) {
		this.lon = lon;
		this.lat = lat;
	}

	/**
	 * Returns the GeoLocation instance as a string.
	 */
	@Override
	public String toString() {
		return "Lat: " + lat + ", Lon: " + lon;
	}

	/**
	 * Returns the longitude as a Double.
	 */
	public Double toLongitude() {
		return Double.valueOf(lon);
	}

	/**
	 * Returns the latitude as a Double.
	 */
	public Double toLatitude() {
		return Double.valueOf(lat);
	}

	/**
	 * Gets a GeoLocation from the specified address.
	 * Uses Google Maps API to encode the address and send an HTTP request.
	 * Processes based on the response status code.
	 */
	public static GeoLocation getGeoLocation(String address) throws IOException, InterruptedException {
		HttpClient client = HttpClient.newHttpClient();
		HttpRequest request = HttpRequest.newBuilder()
				.uri(URI.create("http://maps.google.com/maps/geo?q=" + URLEncoder.encode(address, ENCODING)
						+ "&output=csv&key=" + KEY))
				.build();

		HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
		String line = response.body();
		GeoLocation location = null;
		int statusCode = Integer.parseInt(line.substring(0, 3));
		if (statusCode == 200) {
			// If status code is 200, extract latitude and longitude from response
			location = new GeoLocation(
					line.substring(CSV_PREFIX.length(), line.indexOf(',', CSV_PREFIX.length())),
					line.substring(line.indexOf(',', CSV_PREFIX.length()) + 1, line.length()));
		} else {
			// Throw exception based on status code
			switch (statusCode) {
				case 400:
					throw new IOException("Bad Request");
				case 500:
					throw new IOException("Unknown error from Google Encoder");
				case 601:
					throw new IOException("Missing query");
				case 602:
					return null;
				case 603:
					throw new IOException("Legal problem");
				case 604:
					throw new IOException("No route");
				case 610:
					throw new IOException("Bad key");
				case 620:
					throw new IOException("Too many queries");
				default:
					throw new IOException("Unexpected status code: " + statusCode);
			}
		}
		return location;
	}
}
